on:
  workflow_call:
  push:
    tags:
      - 'v[0-9]+'
      - 'v[0-9]+-*'
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-*'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    branches:
      - '**'
name: linkinator
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - uses: JustinBeckwith/linkinator-action@v1
#        with:
#          config: 'linkinator.config.json'


      - uses: actions/setup-node@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
#        with:
#          node-version: ${{ matrix.node-version }}

      - run: |
          npm install linkinator
          npx linkinator --recurse --verbosity error https://dev3.eodatahub.org.uk

      - run: |
          python3 link_checker/__main__.py https://dev3.eodatahub.org.uk

